ERROR:root:password
ERROR:root:Try with handle: <bound method AccessTokenView.password of <provider.oauth2.views.AccessTokenView object at 0x2b0f00007d10>> and grant_type password
ERROR:root:In PASSWORD
ERROR:root:In PasswordGrantForm
[04/Sep/2015 12:00:50] "POST /oauth2/access_token/ HTTP/1.1" 200 124
ERROR:root:Taskgroup from token: crs4
ERROR Internal Server Error: /teleconsultation/today/open/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smonni/HF/HF/MOST/git_clones/most-demo/server/most/web/authentication/decorators.py", line 49, in wrapper
    return method(request, *args, **kwargs)
  File "/home/smonni/HF/HF/MOST/git_clones/most-demo/server/most/web/teleconsultation/views.py", line 362, in get_open_teleconsultations
    return HttpResponse(json.dumps({'success': True, 'data': result}), content_type="application/json")
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <MostUser: ecografista ecografista> is not JSON serializable
ERROR Internal Server Error: /teleconsultation/today/open/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smonni/HF/HF/MOST/git_clones/most-demo/server/most/web/authentication/decorators.py", line 49, in wrapper
    return method(request, *args, **kwargs)
  File "/home/smonni/HF/HF/MOST/git_clones/most-demo/server/most/web/teleconsultation/views.py", line 362, in get_open_teleconsultations
    return HttpResponse(json.dumps({'success': True, 'data': result}), content_type="application/json")
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <MostUser: ecografista ecografista> is not JSON serializable
ERROR:django.request:Internal Server Error: /teleconsultation/today/open/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smonni/HF/HF/MOST/git_clones/most-demo/server/most/web/authentication/decorators.py", line 49, in wrapper
    return method(request, *args, **kwargs)
  File "/home/smonni/HF/HF/MOST/git_clones/most-demo/server/most/web/teleconsultation/views.py", line 362, in get_open_teleconsultations
    return HttpResponse(json.dumps({'success': True, 'data': result}), content_type="application/json")
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <MostUser: ecografista ecografista> is not JSON serializable
[04/Sep/2015 12:00:50] "GET /teleconsultation/today/open/?access_token=ad04f1e1c02513f26258f400eccbccd7efb27297 HTTP/1.1" 500 138493
^A
